# Native R Travis Github
language: r
cache: packages
#r:
#  - oldrel
#  - release
#  - devel
  
jobs:
  include:
    - stage: release
      r: release
      after_success: 
      - ls
      - echo $NOT_CRAN
      - Rscript -e 'covr::coveralls()' 
    - stage: CRAN
      r: release
      env:
        - _R_CHECK_CRAN_INCOMING_=true
      before_script: 
        - export NOT_CRAN=false # Currently this env variable needs to be set here.
      after_success: 
      - echo $NOT_CRAN
      if: branch = master OR branch = test
    - stage: MacOS X
      os: osx
      r: release
      if: branch = master OR branch = test      
    - stage: oldrel
      r: oldrel
      if: branch = master OR branch = test
    - stage: oldest
      r: 3.2
      if: branch = master OR branch = test
    - stage: devel
      r: devel
      if: branch = master OR branch = test

# Be strict when checking our package
warnings_are_errors: true
r_packages:
  - devtools

r_github_packages:
  - jimhester/covr

notifications:
  email:
    on_success: change
    on_failure: change
